version: '2'
services:
  openldap:
    image: osixia/openldap:1.1.8
    restart: always
    volumes:
      - openldap-lib:/var/lib/ldap:Z
      - openldap-slapd:/etc/ldap/slapd.d:Z
    environment:
      - LDAP_TLS=false
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "domain,application,component,stage,os"
    labels:
      domain: example.com
      application: openldap
      component: openldap
      stage: production
      os: debian