version: '2'
services:
  openldap:
    image: osixia/openldap:1.1.8
    restart: always
    volumes:
      - /docker-containers/openldap/data/lib:/var/lib/ldap:Z
      - /docker-containers/openldap/data/slapd:/etc/ldap/slapd.d:Z
    environment:
      - LDAP_TLS=false
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly