version: '2'
services:
  jenkins-master:
    image: m00re/jenkins-docker:2.46.3-alpine
    restart: always
    volumes:
      - jenkins-master:/var/jenkins_home:Z
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "domain,application,component,stage,os"
    labels:
      domain: example.com
      application: jenkins
      component: master
      stage: production
      os: alpine
    environment:
      - JAVA_VM_PARAMETERS=-Xmx1024m -Xms512m
      - JENKINS_PARAMETERS=
      - JENKINS_MASTER_EXECUTORS=0
      - JENKINS_SLAVEPORT=50000
      - JENKINS_PLUGINS=git-plugin ldap-plugin
      - JENKINS_CERTIFICATE_DNAME=
      - JENKINS_LOG_FILE=
      - JENKINS_USER_NAMES=
      - JENKINS_USER_PERMISSIONS=
      - JENKINS_USER_PASSWORDS=
      - JENKINS_GROUP_NAMES=jenkins-slaves,developers
      - JENKINS_GROUP_PERMISSIONS=jenkins.model.Jenkins.READ:hudson.model.Computer.CONNECT:hudson.model.Computer.DISCONNECT:hudson.model.Computer.CREATE,jenkins.model.Jenkins.READ
