version: '2'
services:

  jenkins-slave-vagrant:
    image: m00re/jenkins-slave-hashicorp:3.3
    restart: always
    environment:
      - SWARM_VM_PARAMETERS=
      - SWARM_MASTER_URL=
      - SWARM_CLIENT_PARAMETERS=
      - SWARM_JENKINS_USER=swarm
      - SWARM_CLIENT_EXECUTORS=1
      - SWARM_CLIENT_LABELS=vagrant packer virtualbox
    volumes:
      - /dev/vboxdrv:/dev/vboxdrv
    privileged: true
