version: '2'
services:

  jenkins-slave-vagrant:
    image: m00re/jenkins-slave-hashicorp:3.6
    restart: always
    environment:
      - SWARM_VM_PARAMETERS=
      - SWARM_MASTER_URL=
      - SWARM_CLIENT_PARAMETERS=
      - SWARM_JENKINS_USER=swarm
      - SWARM_CLIENT_EXECUTORS=1
      - SWARM_CLIENT_LABELS=vagrant packer virtualbox
      - VAGRANT_ADD_CURL_NETRC_HACK=true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "domain,application,component,stage,os"
    labels:
      domain: example.com
      application: jenkins
      component: slave
      stage: production
      os: centos
    volumes:
      - /dev/vboxdrv:/dev/vboxdrv
    privileged: true

  jenkins-slave-javaee:
    image: m00re/jenkins-slave-javaee:3.6
    restart: always
    environment:
      - SWARM_VM_PARAMETERS=
      - SWARM_MASTER_URL=
      - SWARM_CLIENT_PARAMETERS=
      - SWARM_JENKINS_USER=swarm
      - SWARM_CLIENT_EXECUTORS=1
      - SWARM_CLIENT_LABELS=openjdk gradle git docker
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "domain,application,component,stage,os"
    labels:
      domain: example.com
      application: jenkins
      component: slave
      stage: production
      os: centos
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-slave-sphinx:
    image: m00re/jenkins-slave-sphinx:1.6.3-2
    restart: always
    volumes:
      - ./ssh-keypairs/id_ed25519:/inject/.ssh/id_ed25519:Z
      - ./ssh-keypairs/id_ed25519.pub:/inject/.ssh/id_ed25519.pub:Z
      - ./known_hosts:/inject/.ssh/known_hosts:Z
    environment:
      - SWARM_VM_PARAMETERS=
      - SWARM_MASTER_URL=
      - SWARM_CLIENT_PARAMETERS=
      - SWARM_JENKINS_USER=swarm
      - SWARM_CLIENT_EXECUTORS=1
      - SWARM_CLIENT_LABELS=doxygen sphinx
      - IMPORT_HOME_FROM=/inject
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "domain,application,component,stage,os"
    labels:
      domain: example.com
      application: jenkins
      component: slave
      stage: production
      os: centos
