version: '2'
services:

  jenkins-slave-vagrant:
    image: m00re/jenkins-slave-hashicorp:3.4
    restart: always
    environment:
      - SWARM_VM_PARAMETERS=
      - SWARM_MASTER_URL=
      - SWARM_CLIENT_PARAMETERS=
      - SWARM_JENKINS_USER=swarm
      - SWARM_CLIENT_EXECUTORS=1
      - SWARM_CLIENT_LABELS=vagrant packer virtualbox
      - VAGRANT_ADD_CURL_NETRC_HACK=true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "domain,application,component,stage,os"
    labels:
      domain: example.com
      application: jenkins
      component: slave
      stage: production
      os: alpine
    volumes:
      - /dev/vboxdrv:/dev/vboxdrv
    privileged: true
