version: '2'
services:
  taiga-db:
    image: postgres:9.6.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
    volumes:
      - /docker-containers/taiga/data/db:/var/lib/postgresql/data
      - /docker-containers/taiga/backups:/backups

  taiga:
    image: m00re/taiga:3.1.0-ldap
    restart: always
    environment:
      - TAIGA_DB_HOST=taiga-db
      - TAIGA_DB_NAME=taiga
      - TAIGA_DB_USER=taiga
      - TAIGA_PUBLIC_REGISTER_ENABLED=false
      - TAIGA_BACKEND_DEBUG=false
      - TAIGA_FRONTEND_DEBUG=false
      - TAIGA_FEEDBACK_ENABLED=false
      - TAIGA_DEFAULT_LANGUAGE=de
      - TAIGA_SSL=true
      - TAIGA_DEFAULT_THEME=material-design
    volumes:
      - /docker-containers/taiga/data/media:/taiga.io/taiga-back/media
