version: '2'
services:
  taiga-db:
    image: postgres:9.6.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
    volumes:
      - taiga-db:/var/lib/postgresql/data:Z
      - taiga-backups:/backups:Z
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "domain,application,component,stage,os"
    labels:
      domain: projects.datagnan.com
      application: taiga
      component: postgresql
      stage: production
      os: alpine

  taiga:
    image: m00re/taiga:3.1.0-ldap
    restart: always
    environment:
      - TAIGA_DB_HOST=taiga-db
      - TAIGA_DB_NAME=taiga
      - TAIGA_DB_USER=taiga
      - TAIGA_PUBLIC_REGISTER_ENABLED=false
      - TAIGA_BACKEND_DEBUG=false
      - TAIGA_FRONTEND_DEBUG=false
      - TAIGA_FEEDBACK_ENABLED=false
      - TAIGA_DEFAULT_LANGUAGE=de
      - TAIGA_SSL=true
      - TAIGA_DEFAULT_THEME=material-design
    volumes:
      - taiga-media:/taiga.io/taiga-back/media:Z
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        labels: "domain,application,component,stage,os"
    labels:
      domain: projects.datagnan.com
      application: taiga
      component: taiga
      stage: production
      os: alpine
